server:
  port: 7688

application:
  pool-size: 4
  batch-size: 1000
  input-directories:
    cim10: ./data/input
  success-directory: <path_to_success_directory>
  failure-directory: <path_to_failure_directory>

camel:
  springboot:
    name: referential-load

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost/db?serverTimezone=Europe/Paris&useCompression=true&allowMultiQueries=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

management:
  endpoints:
    web:
      exposure:
        include:
          health, jolokia