server:
  port: 7688

spring:
  profiles:
    active: dev

application:
  pool-size: 4
  batch-size: 1000
  input-directories:
    cim10: ./data/input
  success-directory: <path_to_success_directory>
  failure-directory: <path_to_failure_directory>

camel:
  springboot:
    name: referential-load

management:
  endpoints:
    web:
      exposure:
        include:
          health, jolokia